language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "mDSDikWs9pyYlYY7RBmrdTXkpI14f4x+K+HnZ5JGtclwkP47MMWmsj20wnEfb2+LcF7X12wCQI280crCTHYAUego2IHOoE214VT5vTeuu+y9OO5JNsTyhq+Xo2juy+lSYJsBajhi3XjGfjM+GuMQ6ncPZx6TH6dpAxhWv3q0DO/A0i2jscxcGRIOMeFeQVPN8rpXAqVSOGpuJbhIPNeAETjUhn/vnok/nvb/Zw21hWnFtshYu6iqoNzJLBgLbTz//OskZqiS0KUFY46GDlmi3pXGyj8ZOnwvlP+VYdyyx1rHm6NpW4CF5inUBFOoqXOo2622o7K5YNZ4jJKHkQpz4eyzT1EMtlI4cK6UcQQtLv5v9MHbEtFPEoP+ASISv+PpmTjDBNJiwgCk3Y+nbRLhB55Gyg8YNW6GHneruEIVCYhyXV49I54kS20gA1Vr+FgqDPkwl/cZR/Xpn0B0hEyzZ4FKQIjrDuHAaF8OFfDkxczHs0qhS/O4oJXMCp5gCbvgAQ4OfyNJQqFXiyacbQ2C7Z5jcbnATpPDFIuTeuEB+oVkwy5TtI6L6DPJ/0BzIn2lQ99TmIXHRcOc9aWA1uFpz6XyB8t+2uVPy4mpdum/d9v0pToTpEH1p1oXmcvC0i7vq6a4echxYQNCtVVqjmU+tbGVnpRplgv/Onoq34Xg0Mg="
env:
  secure: "MhEHxKnSOKzX7/2vnWji39nXM8h2NFmA3JBHnlSw872lQItHhOq8X38cF30e+5Fd5YGie7TUYocHbWsWiam7IrcukFw5v/MCZKaRHIjde0xj+26FNw7Yeb3Ttt8C6Ikx764QG0Rgtk9gCazJk1AnIkZ06hAa3UdFarVr1Ao5z6mkrC9R4n0UC7/lsAlEZTPSYgKOh8w6B47eO14BvsnAEfy4vpqxBV8uo7oCq+kXOraa4cuv7vOn0MFKKp7EE+JMzU86Eg0ixcTgLjjJDcO/LmXG1x9Ix+OObSAmGdon1kWDoABUIiFv78ISIkmh8X7jKEnSwf/Dm9TygvcVIxChU1T/c/eyaOTS0sbNS/1hl7S1ndsliIW0PQaAlDzbd8I3Occ7iv/6pgKxMEqBFTafn/ZmncnBC0eT/CPM/fKGT21EY6sD1U47yzN/hI5Cg40I+TL7t9mgWXMNVSm3CcPoA6XLGCkjR2ShN3KDdNlk2yBR/vNh8CGDVq/vNqIEcV6wyrzCaRhwQ4/tBsaWCiESjtIoyNk2OCu6jL7gbKGTlnpLFQKNRP7Njr+EPkThHaFt4iYb7tnoTpY2ZwJsMGyoep5l1wVFEY+6BufFNqQmQp8hVvNAfe+4RMcOPXU+GfoUnSgJiWhqVlQ8vnZZFtM+oMzm7l1DyA1QiBfRUsREIr4="
