language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MhEHxKnSOKzX7/2vnWji39nXM8h2NFmA3JBHnlSw872lQItHhOq8X38cF30e+5Fd5YGie7TUYocHbWsWiam7IrcukFw5v/MCZKaRHIjde0xj+26FNw7Yeb3Ttt8C6Ikx764QG0Rgtk9gCazJk1AnIkZ06hAa3UdFarVr1Ao5z6mkrC9R4n0UC7/lsAlEZTPSYgKOh8w6B47eO14BvsnAEfy4vpqxBV8uo7oCq+kXOraa4cuv7vOn0MFKKp7EE+JMzU86Eg0ixcTgLjjJDcO/LmXG1x9Ix+OObSAmGdon1kWDoABUIiFv78ISIkmh8X7jKEnSwf/Dm9TygvcVIxChU1T/c/eyaOTS0sbNS/1hl7S1ndsliIW0PQaAlDzbd8I3Occ7iv/6pgKxMEqBFTafn/ZmncnBC0eT/CPM/fKGT21EY6sD1U47yzN/hI5Cg40I+TL7t9mgWXMNVSm3CcPoA6XLGCkjR2ShN3KDdNlk2yBR/vNh8CGDVq/vNqIEcV6wyrzCaRhwQ4/tBsaWCiESjtIoyNk2OCu6jL7gbKGTlnpLFQKNRP7Njr+EPkThHaFt4iYb7tnoTpY2ZwJsMGyoep5l1wVFEY+6BufFNqQmQp8hVvNAfe+4RMcOPXU+GfoUnSgJiWhqVlQ8vnZZFtM+oMzm7l1DyA1QiBfRUsREIr4="
env:
  secure: "gHgpf7dyzY24rxtpS+/GxCPNj/CMb3tQ4IjWY1kjJh7ggukyrGadX+iS5uX7i/tag5+Vrp86V1mF95E/uunIrX3XA1DA1I8nXGK358Ms/zjY24JGmvx55FyarP55taSEeoqsKtop5DQlD1cD4MZW/KaZlF39BFI1Zl1dsYigW2FMBCoekEOUDKP+1HlRWMFF/OYUgGVnzw/KaRY5CsKQMU0FlfW8IZfLySbzhY3POgdOHq+CNRAzde7U+7Ij9KvXuIS6B8TP4K2ZO65wt1kqOQK+YgInGGADSalepHLvsej+qMI4LMRACdBQA7Lrxzh4i7gl1Yn4ePUNlDGe4+14iK360IYKVRksasgBd8RpSIXTnWbtvFpN7xd90Ntk87IWjNFiWeIPMQjrpL2H35aue6poqWLfkjHwlqEl5cATGl0lYNNVrPD/NdTJSr2Qfnq1CjpLSRgSVgtUduT6e9Qn3QuceTQSVyut29pXLfRPyWZZX+jrWycio98nUvrsqWqHLSxU3ZEO+Z+TdPYI6t1+lFKCJo1Mw/GiEwpColKOGlmXzFGJ40W9gVV8KbmARzsLlacLnU/bxo9JNFogtZYM4vb7UX9V96hhHPz0P72yw0gq3Ybdqkj2EvyAzzXrQ59DrBa3SFaCQ3il65P6Rp588fG1IOdoA8cTJ1NWmANjkbM="
