language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: NC6ZOPjvPlWaes42ktEXqoDIO7NYMhc/n5wYb7HaitGYWXsHKAI6lIZwNiFZpZ8OtLC4cneh44JqtOb13a/XtlN+uF/zgbDWbCNHze7xQLrHuF+3zn+5mFGGNgfR6MHn6QWGP8P1oRy9BYnHtfI2RDI8iKkmaDUsS7wa/WiOvHQZHFgKg38PFsuBfW+kuXwKPLZAPcwa5uAxeOd4Z7+HZ1WX/mGY3xb+y5coSL3ihbh/ocnMalFc0btr2RrE03TEBIY3wRdJZbnFP+NGrs8kKPnRl1IJu18WKF1WH+UWLJ81+a5r5e+afraEG5KeHvytd/WaCkzR/V2A4n/H5aAOzkhm9AzU5qJZEHYaFKyktgHf+1FLjzDUS/Yc4e3MiYk6BJpAYKNQWfpaHOQXvr/5ML/FyoKO3+mOMYahwQ+Z5AWRetC1MBvZDVB0KAxIdzyfyvV7cOUPelut9+XpNddLANNQmDwDteqFB3L1GkShNzDedWpcTM/FG22dJvVf6vZMRtOCRB2S0rNVQmpyfGINrV3enxO+/PSdhjM+lmx5k0VjVJlTBbx97Gkozvm9cT2lIhbrLsntfz7JlUYgONS3iNrfcsl23Zmua6J+HVQYOYStU5tKdIs/CZ3TkOKcKrETlCPgJsC6j09Kr7yp06ooIsV7s5AHhooA+GdYokS/phA=
  - secure: CsnljruDIjNyPi9t2aX0Lg+k/vXOifDhQ+CzL+3MRjPz9CjG1KClu3+ImSHbOlvUZkBkPh7KU71i0JeiZWYnvLtWkHpm1YugVyOalb3CQLkKjgTioqupQEc1h5Q3kEA0v/Sq8EBtxVoxygyoKFrELuPFCHmaMr2KhNpIrbnKsBTjvwI9Dv/7yxn8iUbLic6r8NOC4TdoExWtkJlSQQLAlC75sm1dH+p2I+uYZ4SeyrJmJHTUkNdZytjspbtKFmYQgM8amRoIDLM5drk/WLW43AQWAWYg5z/jx2oqYrnPQgpULDavCSRql0mFPXnnVSTJK+DdkmWEmM6LELHEH1nOoD/jVoUplTu2GFkow1+Qri3mxLwlq0Rf7YOhYQ9yLjDSjid4dVScOppCDVfwg8CtNDzjC/UQgT8QiOsVy17d2SZjmh5CXLpBBdyLDNnlKDlUbsG9dNgGNTVLcDmQ5SkHGRXFEkGRc1OR8DlopXkRbaAGZOB30gjyoJ7YeaKgF7ecN1p9IaoT/UtdbkE55uDupzBEis+OuoV05KVkLsTmzjom1NfVxFea+XSGEG2AXJ3qPsa30bNmsxjQZz0itD0Iz3Z7lrHVAlL2ZuO17cNeZ9ZjlFDA/ihpBuIx3DTrSIXYBwy6Mzu5QEFQ/L9KI/hjB2AHO3C2ooKbmFydaedkAIM=
